name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: mkdevyoutube

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.PROJECT}}
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ILoveMkdev
          runtime: java11
          project_id: mkdevyoutube
          entry_point: functions.ILoveMkdev

      - name: make the url aunthenticated
        run: |
          gcloud functions deploy ILoveMkdev --trigger-http --allow-unauthenticated 

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"


